CREATE TABLE IF NOT EXISTS users (
                                     is_active BOOLEAN NOT NULL,
                                     created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     updated_at TIMESTAMP(6) WITH TIME ZONE,
                                     version BIGINT,
                                     avatar_url VARCHAR(500),
                                     display_name VARCHAR(255) NOT NULL UNIQUE,
                                     email VARCHAR(255) NOT NULL UNIQUE,
                                     password VARCHAR(255) NOT NULL,
                                     role VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
                                     PRIMARY KEY (id)
);

INSERT INTO users (
    is_active,
    created_at,
    updated_at,
    version,
    avatar_url,
    display_name,
    email,
    password,
    role
)
VALUES (
           TRUE,
           NOW(),
           NOW(),
           0,
           'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y',
           'Admin',
           'ankit@gmail.com',
           'aerohive',
           'ADMIN'
       ) on conflict (email) do nothing;