CREATE TABLE ingredients
(
    is_active  BOOLEAN                     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME zone NOT NULL,
    id         bigint generated BY DEFAULT AS identity,
    updated_at timestamp(6) WITH TIME zone,
    version    bigint,
    name       VARCHAR(255)                NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE recipe_ingredients
(
    is_active     BOOLEAN                     NOT NULL,
    quantity      NUMERIC(38, 2)              NOT NULL,
    created_at    timestamp(6) WITH TIME zone NOT NULL,
    id            bigint generated BY DEFAULT AS identity,
    ingredient_id bigint,
    recipe_id     bigint,
    updated_at    timestamp(6) WITH TIME zone,
    version       bigint,
    unit          VARCHAR(255)                NOT NULL CHECK ((unit IN ('GRAM',
                                                                        'KILOGRAM',
                                                                        'MILLIGRAM',
                                                                        'MILLILITER',
                                                                        'LITER',
                                                                        'TEASPOON',
                                                                        'TABLESPOON',
                                                                        'CUP',
                                                                        'PIECE',
                                                                        'SLICE',
                                                                        'CLOVE',
                                                                        'PINCH',
                                                                        'DASH',
                                                                        'CAN',
                                                                        'PACKET',
                                                                        'BUNCH'))),
    PRIMARY KEY (id)
);
CREATE TABLE recipe_reviews
(
    is_active     BOOLEAN                     NOT NULL,
    rating        INTEGER                     NOT NULL,
    created_at    timestamp(6) WITH TIME zone NOT NULL,
    helpful_count bigint                      NOT NULL,
    id            bigint generated BY DEFAULT AS identity,
    recipe_id     bigint                      NOT NULL,
    updated_at    timestamp(6) WITH TIME zone,
    user_id       bigint                      NOT NULL,
    version       bigint,
    COMMENT       VARCHAR(2000),
    PRIMARY KEY (id),
    CONSTRAINT uk_recipe_review_user_recipe UNIQUE (recipe_id, user_id)
);
CREATE TABLE recipes
(
    cook_time_minutes INTEGER,
    is_active         BOOLEAN                     NOT NULL,
    prep_time_minutes INTEGER,
    servings          INTEGER,
    created_at        timestamp(6) WITH TIME zone NOT NULL,
    id                bigint generated BY DEFAULT AS identity,
    updated_at        timestamp(6) WITH TIME zone,
    version           bigint,
    description       VARCHAR(2000),
    difficulty_level  VARCHAR(255)                NOT NULL CHECK ((difficulty_level IN ('EASY',
                                                                                        'MEDIUM',
                                                                                        'HARD'))),
    title             VARCHAR(255)                NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE recipe_step
(
    duration_minutes INTEGER,
    is_active        BOOLEAN                     NOT NULL,
    step_number      INTEGER                     NOT NULL,
    created_at       timestamp(6) WITH TIME zone NOT NULL,
    id               bigint generated BY DEFAULT AS identity,
    recipe_id        bigint                      NOT NULL,
    updated_at       timestamp(6) WITH TIME zone,
    version          bigint,
    media_url        VARCHAR(500),
    instruction      VARCHAR(2000)               NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE users
(
    is_active    BOOLEAN                     NOT NULL,
    created_at   timestamp(6) WITH TIME zone NOT NULL,
    id           bigint generated BY DEFAULT AS identity,
    updated_at   timestamp(6) WITH TIME zone,
    version      bigint,
    avatar_url   VARCHAR(500),
    display_name VARCHAR(255)                NOT NULL UNIQUE,
    email        VARCHAR(255)                NOT NULL UNIQUE,
    password     VARCHAR(255)                NOT NULL,
    ROLE         VARCHAR(255)                NOT NULL CHECK ((ROLE IN ('USER',
                                                                       'ADMIN'))),
    PRIMARY KEY (id)
);
CREATE INDEX idx_recipe_review_recipe
    ON recipe_reviews
        (
         recipe_id
            );
CREATE INDEX idx_recipe_review_user
    ON recipe_reviews
        (
         recipe_id,
         user_id
            );
CREATE INDEX idx_review_recipe_created
    ON recipe_reviews
        (
         recipe_id,
         created_at DESC
            );
CREATE INDEX idx_review_rating
    ON recipe_reviews
        (
         recipe_id,
         rating
            );
CREATE INDEX idx_user_display_name
    ON users
        (
         email
            );

ALTER TABLE IF EXISTS recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_ingredient
    FOREIGN KEY (ingredient_id)
    REFERENCES ingredients (id);

ALTER TABLE IF EXISTS recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_recipe
    FOREIGN KEY (recipe_id)
    REFERENCES recipes (id);

ALTER TABLE IF EXISTS recipe_reviews
    ADD CONSTRAINT fk_recipe_reviews_recipe
    FOREIGN KEY (recipe_id)
    REFERENCES recipes (id);

ALTER TABLE IF EXISTS recipe_reviews
    ADD CONSTRAINT fk_recipe_reviews_user
    FOREIGN KEY (user_id)
    REFERENCES users (id);

ALTER TABLE IF EXISTS recipe_step
    ADD CONSTRAINT fk_recipe_step_recipe
    FOREIGN KEY (recipe_id)
    REFERENCES recipes (id);

ALTER TABLE IF EXISTS recipes
    ADD CONSTRAINT uk_recipe_title UNIQUE (title);

ALTER TABLE IF EXISTS ingredients
    ADD CONSTRAINT uk_ingredient_name UNIQUE (name);